import { defineConfig } from 'tsup';

import pkg from './package.json';

export default defineConfig({
  banner: {
    js: '/** Components v' + pkg.version + ' */',
  },
  clean: true,
  dts: true,
  entry: [
    'src/components/button/index.ts',
    'src/components/click-outside-guard/index.ts',
    'src/components/dialog/index.ts',
    'src/components/divider/index.ts',
    'src/components/field/index.ts',
    'src/components/flex/index.ts',
    'src/components/grid/index.ts',
    'src/components/icon/index.ts',
    'src/components/idle/index.ts',
    'src/components/input/index.ts',
    'src/components/menu/index.ts',
    'src/components/navigation/index.ts',
    'src/components/number-input/index.ts',
    'src/components/order/index.ts',
    'src/components/overlay/index.ts',
    'src/components/pagination/index.ts',
    'src/components/range/index.ts',
    'src/components/select/index.ts',
    'src/components/slider/index.ts',
    'src/components/status/index.ts',
    'src/components/switch/index.ts',
    'src/components/table/index.ts',
    'src/components/text/index.ts',
    'src/components/textarea/index.ts',
    'src/components/toast/index.ts',
    'src/components/tooltip/index.ts',
    'src/index.ts',
    'src/theme.ts',
  ],
  format: ['cjs', 'esm'],
  legacyOutput: true,
  minify: true,
  sourcemap: true,
  splitting: false,
  target: 'node12',
});
